### ISSUE TITLE
regexp-clone error

### ISSUE THREAD

**Issue by derekzhan** [mz121star/NJBlog#7]
我按照说明文档来操作的，等到执行node app.js 时出现以下错误：
D:\code\mycode\NJBlog>node app.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'regexp-clone'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\code\mycode\NJBlog\node_modules\mongoose\lib\utils.js:7:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

帮忙看下，谢谢了

**Comment by mz121star** [comment]
缺少 regexp-clone  用 npm install regexp-clone 装一下
